export function getDomRefs() {
  return {
    page: document.querySelector('.js-page'),
    dockButtons: document.querySelectorAll('.js-dock-btn'),
    focusToggle: document.querySelector('.js-focus-toggle'),
    searchInput: document.querySelector('.js-search-input'),
    listEl: document.querySelector('.js-stream-list'),
    resultsMetaEl: document.querySelector('.js-results-meta'),
    sortButtons: document.querySelectorAll('.js-sort-btn'),
    ageButtons: document.querySelectorAll('.js-age-btn'),
    languageSelect: document.querySelector('.js-language-select'),
    platformSelect: document.querySelector('.js-platform-select'),
    slotButtons: document.querySelectorAll('.js-slot-btn'),
    slotEls: document.querySelectorAll('.js-slot'),
    authLoginBtn: document.querySelector('.js-auth-login'),
    authLogoutBtn: document.querySelector('.js-auth-logout'),
    authUserEl: document.querySelector('.js-auth-user'),
    authAvatarEl: document.querySelector('.js-auth-avatar'),
    authNameEl: document.querySelector('.js-auth-name'),
    followedToggleBtn: document.querySelector('.js-followed-toggle'),
    followedList: document.querySelector('.js-followed-list'),
    navLinks: document.querySelectorAll('.js-nav-link'),
    directoryPage: document.querySelector('.js-directory-page'),
    categoriesPage: document.querySelector('.js-categories-page'),
    categoryGrid: document.querySelector('.js-category-grid'),
    categoryMetaEl: document.querySelector('.js-category-meta'),
    categorySortButtons: document.querySelectorAll('.js-category-sort-btn'),
    categoryTagList: document.querySelector('.js-category-tag-list'),
    categoryActiveList: document.querySelector('.js-category-active'),
    categoryClearBtn: document.querySelector('.js-category-clear'),
  };
}
